---
- hosts: 172.31.18.254
  become: yes
  tasks:
   - name: install git
     apt:
      name: git
      tags: 1st

   - name: install wget
     apt: 
      name: wget
     tags: 2nd

   - name: install tree
     apt:
      name: tree
     tags: 3rd
      