---
- hosts: 172.31.18.254
  become: yes
  tasks:
   - name: install git
     apt:
      name: git
      tags:
        - git

   - name: install wget
     apt: 
      name: wget
     tags:
      - wget
      

   - name: install tree
     apt:
      name: tree
     tags:
      - tree 