---
- hosts: webservers
  become: yes
  tasks:
   - name: install webserver on ubuntu16
     apt:
      name: "{{webserversOnubuntu}}"
      state: present
     when: ansible_os_family =="Debian"
   - name: start webserver on ubuntu
     service:
      name:  "{{webserversOnubuntu}}"
      state: started
     when: ansible_os_family =="Debian"

   - name: install webserver on RedHat8
     yum:
      name: "{{webserversOnRedHat}}"
      state: present
     when: ansible_os_family =="RedHat" 
   - name: start webserver on RedHat8
     service:
      name: "{{webserversOnRedHat}}"
      state: started
     when: ansible_os_family =="RedHat" 




