- name: extravars playbook
  hosts: all
  tasks:
  - name: create a file using  extravars
    file:
      name: "{{filename}}"
      owner: "{{ownername}}"
      group: "{{groupname}}"
      mode: "{{perm}}"
      state: touch
    register: extra_vars
- name: printing the value
  debug:
    msg: "{{extra_vars}}"
