- name: creating first file
  hosts: all
  become: yes
  tasks:
  # - name: creating directory on user sai
  #   file:
  #     path: ~/filemodule
  #     state: directory
  #     owner: sai
  #     group: sai
  #     mode: 0755
  # - name: creating a file inside the filemodule dir
  #   file:
  #     path: ~/filemodule/hima.txt
  #     state: touch
  #     mode: 0755
  - name: move hima file to filemodule directory
    copy:
      src: ~/hima.txt
      dest: ~/filemodule/hima.txt
      owner: sai
      group: sai
      mode: 0755
      remote_src: true
      
