- name: creating first file
  hosts: all
  become: yes
  tasks:
  # - name: creating directory on user sai
  #   file:
  #     path: ~/filemodule
  #     state: directory
  #     owner: sai
  #     group: sai
  #     mode: 0755
  # - name: creating a file inside the filemodule dir
  #   file:
  #     path: ~/filemodule/hima.txt
  #     state: touch
  #     mode: 0755
  - name: creating a file on filemodule
    file: 
      path: /home/sai/filemodule/himafile.txt
      state: touch
      owner: sai
      group: sai
      mode: 0655
    register: copystatus
  - name: move hima file to filemodule directory  
    copy:
      src: /home/sai/filemodule/himafile.txt
      dest: /~/
      owner: sai
      group: sai
      mode: 0755
      remote_src: true
      register: copystatus
  - name: print status
    debug:
      msg: "{{copystatus}}"
      
