- name: creating first file
  hosts: all
  become: yes
  tasks:
  - name: creating directory on user sai
    file:
      path : /home/sai/filemodule
      state: directory
      mode: 0755
  -name: creating a file inside the filemodule dir  
    file:  
      path: /home/sai/hima.txt
      state: touch
      mode: 0755

